### ISSUE TITLE
AlphaComplex or SimplexTree numeric issues

### ISSUE THREAD

**Issue by jasnaurbancic** [GUDHI/gudhi-devel#107]
I have encountered some trouble with numeric stability in AlphaComplex. I attached the minimal code example below. Briefly what I did: I generate a set of points (sin(x), sin(x + PI)), which is the same as (sin(x), -sin(x)). However, when I build AlphaComplex and then a simplex tree, I get out different filtrations for these two embeddings. In case of sin(x + PI), 3-simplices appear, which should not be there as all the points are on the same line. Is there something I am doing wrong?

Minimal code example:
```import gudhi
from gudhi import AlphaComplex, SimplexTree

import math
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

#generate periodic signal
time = np.arange(0, 10, 1)
signal = [math.sin(x) for x in time]
delta = math.pi
delayed = [math.sin(x + delta) for x in time]

#construct embedding
embedding1 = [[signal[i], -signal[i]] for i in range(len(time))]
embedding2 = [[signal[i], delayed[i]] for i in range(len(time))]

fmt = 'Point: %2d | X1: %.16f | Y1: %.16f | X2: %.16f | Y2: %.16f'
print('Printing points | Embedding 1 | Embedding 2')
for i in range(len(time)):
    print(fmt % (i, embedding1[i][0], embedding1[i][1], embedding2[i][0], embedding2[i][1]))

#build alpha complex and simplex tree
alpha_complex1 = AlphaComplex(points=embedding1)
simplex_tree1 = alpha_complex1.create_simplex_tree()

alpha_complex2 = AlphaComplex(points=embedding2)
simplex_tree2 = alpha_complex2.create_simplex_tree()

fmt = '%s -> %f'
print('Filtration for embedding1:')
for filtered_value in simplex_tree1.get_filtration():
    print(fmt % tuple(filtered_value))

print('Filtration for embedding2:')
for filtered_value in simplex_tree2.get_filtration():
    print(fmt % tuple(filtered_value))

diag1 = simplex_tree1.persistence()
diag2 = simplex_tree2.persistence()

pplot1 = gudhi.plot_persistence_diagram(diag1, max_intervals=10, legend=True)
pplot1.show()
pplot2 = gudhi.plot_persistence_diagram(diag2, max_intervals=10, legend=True)
pplot2.show()
```

**Comment by mglisse** [comment]
Hello,
first, in the second case, your points do **not** lie exactly on a line, because of numerical accuracy (in python, computing x+delta is not exact, nor is math.sin). So it is normal that you get triangles. However, when computing persistence, those triangles should probably (I didn't check this specific case) only create intervals of length 0 (on the diagonal), and this is a numerical issue in gudhi. We have been aware of it since the beginning, and can finally fix it soon. For the utility alpha_complex_persistence.cpp, it is as simple as replacing `Epick_d` with `Epeck_d` (works best with CGAL-5.0). For the python plugin, it sadly requires a little bit more work. We will keep this report open and check the new code on your data as soon as it is ready.

**Comment by VincentRouvreau** [comment]
Hello,

if you are not familiar with C++, I created the following gist : [AlphaComplex or SimplexTree numeric issues #107 investigation](https://gist.github.com/VincentRouvreau/61d8e259d6ddce72451fd320361506fb)

The files embed1.off and embed2.off were created from your python code.

I compiled Inexact_alpha_complex_persistence.cpp (`Epick_d`)and Exact_alpha_complex_persistence.cpp (`Epeck_d`) with CGAL 4.11.

You will see that the exact version has no effect on embed1, whereas on embed2, the following persistence pairs disappear:
```
11  1 0.939451 1.44601e+30 
11  1 0.509704 3.97576e+29 
11  1 0.996663 1.25845 
```
