### ISSUE TITLE
Tests `Bottleneck_distance_test_unit` and `Persistence_intervals_test_unit` fail on x86/i386

### ISSUE THREAD

**Issue by gspr** [GUDHI/gudhi-devel#118]
As of GUDHI 3.0.0, the tests `Bottleneck_distance_test_unit` and `Persistence_intervals_test_unit` fail on 32 bit x86 ("i386"). All of the other 177 tests pass. From what I can tell, these tests were not present in 2.3.0. There are no error messages, but looking at the code for the latter test, my first hunch would be some rounding issue.

PS: I do not personally care about 32 bit x86, but the failure arises as part of upgrading the GUDHI Debian package to 3.0.0. The failure might indicate general brittleness of the test, so it may still be interesting to fix it even though the architecture in question is becoming increasingly marginal.

**Comment by mglisse** [comment]
If these are tests that test for equality between floats, we were planning to fix them (check that the difference is small), but delayed because they were not failing yet. This gives us some motivation, thanks.

**Comment by mglisse** [comment]
> Running 5 test cases...
> bottleneck_unit_test.cpp(62): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(0, 0)) > 0 has failed
> bottleneck_unit_test.cpp(67): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(0, (n1 + n2) - 1)) > 0 has failed
> bottleneck_unit_test.cpp(70): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(n1, n1)) > 0 has failed
> bottleneck_unit_test.cpp(71): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(n1, n2 - 1)) > 0 has failed
> bottleneck_unit_test.cpp(72): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(n1, n2)) > 0 has failed
> bottleneck_unit_test.cpp(73): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance(n1, (n1 + n2) - 1)) > 0 has failed
> bottleneck_unit_test.cpp(74): error: in "persistence_graph": check std::count(d.begin(), d.end(), g.distance((n1 + n2) - 1, 0)) > 0 has failed

It requires at least -O2 to fail with gcc, or -O1 with clang.

**Comment by mglisse** [comment]
That's the usual x87 issue where `a+b==a+b` can return false (without any NaN) because one of them was stored in memory (and thus rounded to 64 bits) while the other is still in a register (80 bits). If I replace `g.distance(0, 0)` with `protect(g.distance(0, 0))` where `double protect(double x){volatile double e=x;return e;}`, the error disappears. `-ffloat-store` also works (I thought it was only supported for C, not C++ ?!). In any case, the changes should be only in the testsuite, the library code is fine.
I expect you are only getting this error on x86 (and m68k, but that's not an official Debian port).

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> That's the usual x87 issue where `a+b==a+b` can return false (without any NaN) because one of them was stored in memory (and thus rounded to 64 bits) while the other is still in a register (80 bits). If I replace `g.distance(0, 0)` with `protect(g.distance(0, 0))` where `double protect(double x){volatile double e=x;return e;}`, the error disappears. `-ffloat-store` also works (I thought it was only supported for C, not C++ ?!). In any case, the changes should be only in the testsuite, the library code is fine.

Ah, ok, thanks. That's very enlightening.

> I expect you are only getting this error on x86 (and m68k, but that's not an official Debian port).

Correct, x86 only (I'm not currently building on m68k due to some
missing dependencies at the moment, and as you say it's not an official
port).

**Comment by VincentRouvreau** [comment]
Do you have an idea of what needs to be protected on persistence_intervals_test ?
I have no x86 available for the moment.

**Comment by gspr** [comment]
Vincent Rouvreau <notifications@github.com> writes:

> Do you have an idea of what needs to be protected on persistence_intervals_test ?
> I have no x86 available for the moment.

Sorry, I don't. I just know that the tests
`Bottleneck_distance_test_unit` and `Persistence_intervals_test_unit`
are the failing ones.

**Comment by gspr** [comment]
Vincent Rouvreau <notifications@github.com> writes:

> Do you have an idea of what needs to be protected on persistence_intervals_test ?
> I have no x86 available for the moment.

I'm happy to test any proposed changes in an x86 VM though, if you want.

**Comment by mglisse** [comment]
> persistence_intervals_test.cpp(93): error: in "check_histogram_of_lengths": check histogram[i] == template_histogram[i] has failed
> persistence_intervals_test.cpp(93): error: in "check_histogram_of_lengths": check histogram[i] == template_histogram[i] has failed
> persistence_intervals_test.cpp(114): error: in "check_cumulative_histograms_of_lengths": check cumulative_histogram[i] == template_cumulative_histogram[i] has failed

That's more complicated. histogram_of_lengths does something a bit misguided I think. There is a bunch of non-negative numbers. It picks the maximum and divides them all by this maximum, so they are in [0,1]. Then it creates bins (let me take number_of_bins=4) to contain those points: [0,.25), [.25,.5), [.5,.75), [.75,1), [1, 1.25). Yes, there is an extra bin that just counts the multiplicity of the maximum. On x86, since max is actually the result of a subtraction, it happens that max/max is not 1 but .999999. We thus don't get the bin content that the test expects. In my opinion, the last bin should just disappear and its content be added to the previous one. At least this way `number_of_bins` would not be a lie. `result[number_of_bins-1]+=result[number_of_bins]; result.resize(number_of_bins);`

(all those *push_back*s to fill a vector are so C++98...)

**Comment by VincentRouvreau** [comment]
Thanks for the investigation. I did the modifications you are proposing on #164
