### ISSUE TITLE
[python representations] Gracefully handling dependencies

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#149]
Currently, if I compiled gudhi without CGAL, `import gudhi.representations` prints
> Gudhi built without CGAL: BottleneckDistance will return a null matrix

(even if I don't care about BottleneckDistance and never want to use it) and every call to BottleneckDistance.transform prints again
> Gudhi required---returning null matrix

That may be ok for CGAL, since a lot in gudhi depends on it, but it will not scale well. Soon we will want to add a similar WassersteinDistance class. The case is slightly different (run-time vs compile-time dependency), but related. The discussion at the time was that we should not try to import everything automatically when that implies optional external dependencies (currently POT for wasserstein).

One option that @VincentRouvreau used is to move the optional imports inside the function that uses them. IIRC this is frowned upon, but very convenient. Another option would be to require that the user perform some imports manually for these functions to be available: either they import gudhi.wasserstein and we test if that's available in metrics.py, or we add WassersteinDistance to a separate submodule (`gudhi.representations.wasserstein`?), that does all its imports eagerly, but that isn't auto-imported by anything. gudhi.bottleneck_distance is currently simply absent without CGAL, it would also be possible for BottleneckDistance to do the same somehow.

**Comment by VincentRouvreau** [comment]
@mglisse It is not working like that since 87311ec 
An exception is raised when called (no more messages on `import gudhi.representations`):
```
ImportError: cannot import name 'bottleneck_distance'
```
cf.
https://github.com/GUDHI/gudhi-devel/blob/412469e0e96b4091d3760400ea251b2bf180f1b2/src/python/gudhi/representations/metrics.py#L152-L158
and
https://github.com/GUDHI/gudhi-devel/blob/412469e0e96b4091d3760400ea251b2bf180f1b2/src/python/gudhi/representations/metrics.py#L272-L277
Do you think we can close the issue, or maybe improve the text ?
