### ISSUE TITLE
ctest --output-on-failure

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#168]
It would be nice, for CI, but also for regular development, to see the actual error messages when there are errors. Apparently, this can be achieved by passing `--output-on-failure` as argument to ctest, or setting `CTEST_OUTPUT_ON_FAILURE=plouf` in the environment.

**Comment by VincentRouvreau** [comment]
For regular development, this can only be achieved by the user as the `test` target cannot be modified. Some are proposing to do a [`check` target that does the job](https://stackoverflow.com/questions/16158091/cmake-setting-an-environmental-variable-for-ctest-or-otherwise-getting-failed).
Do you agree to go with this solution ? Or I just modify CI to use `ctest --output-on-failure` instead of `make test` ?

**Comment by mglisse** [comment]
I don't have a strong opinion. Documenting that developers should run the tests with `ctest --output-on-failure ...` (and actually doing that on CI) would be ok I guess (it also makes it easier to pass other arguments like `-j 12`), assuming `make test` does nothing else. I guess make check can also make sense. Maybe it works (on some platforms?) to just set an environment variable from cmake `set(ENV{CTEST_OUTPUT_ON_FAILURE} whatevs)`.

**Comment by VincentRouvreau** [comment]
I tested `make check`, but `make -j 12 check` has no effect. This is not satisfying for me.
Let's document the `ctest --output-on-failure` way to do it.
