### ISSUE TITLE
[Sparse Rips complex] Construction from a distance matrix do not work

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#45]
The following example : https://gist.github.com/VincentRouvreau/4d3f7951fafd4847cd62443a084070e5
shows how to construct a sparse rips complex from a distance matrix.
The crash seems to come related to choose_n_farthest_points function when using a distance matrix.

**Comment by mglisse** [comment]
The program you link to needs arguments at runtime, and you didn't say on which arguments it crashed, so I don't know how to reproduce it (I didn't try).
I think the issue is that read_lower_triangular_matrix_from_csv_file returns half a distance matrix, which is indeed what Sparse_rips documents (copied from Rips most likely), but then Sparse_rips calls choose_n_farthest_points which expects a complete distance function. If that is indeed the issue, two possible fixes are:
- document that we need a full matrix
OR
- in the lambda, before `distance_matrix[j][i];`, do `if(j<i)std::swap(i,j);`
I'll do the second one in the branch where I am already modifying the sparse Rips.

**Comment by VincentRouvreau** [comment]
```
  template <typename DistanceMatrix>
  Sparse_rips_complex(const DistanceMatrix& distance_matrix, double epsilon)
      : Sparse_rips_complex(boost::irange<Vertex_handle>(0, boost::size(distance_matrix)),
                            [&](Vertex_handle i, Vertex_handle j) {
                              if (i == j) return (Filtration_value)0;
                              if (j < i) std::swap(i, j);
                              return distance_matrix[j][i]; }, epsilon) {}

```
fixes the issue
