### ISSUE TITLE
AttributeError: module 'gudhi' has no attribute 'RipsComplex'

### ISSUE THREAD

**Issue by poeiradonorte** [GUDHI/gudhi-devel#559]
Gudhi is installed (conda environment) but this error message persists.
" AttributeError: module 'gudhi' has no attribute 'RipsComplex' "

For example when I access python (version 3.9.7) and apply the command:
" from gudhi import RipsComplex "

Python finds the gudhi.
But when gudhi is called inside a script the Attribute Error occurs.

![Screenshot from 2021-12-20 01-03-46](https://user-images.githubusercontent.com/22729945/146710402-4d80e976-9569-44bc-9aaa-ff9c7c677c1f.png)

**Comment by mglisse** [comment]
What version of gudhi do you have? What version of python does you script use (the system one or the one from conda)? What is your PYTHONPATH for the script? Do you have a directory named gudhi somewhere that could confuse python?

**Comment by poeiradonorte** [comment]
1 - What version of gudhi do you have?
3.4.1

2 - What version of python does you script use (the system one or the one from conda)?
From conda, Python 3.9.7

What is your PYTHONPATH for the script?
/home/leon/miniconda3/lib/python39.zip
/home/leon/miniconda3/lib/python3.9
/home/leon/miniconda3/lib/python3.9/lib-dynload
/home/leon/miniconda3/lib/python3.9/site-packages

3 - Do you have a directory named gudhi somewhere that could confuse python?

/home/leon/gudhi.3.4.1/include/gudhi
/home/leon/gudhi.3.4.1/python/gudhi
/home/leon/miniconda3/pkgs/gudhi-3.4.1-py39h47373e2_1/share/gudhi
/home/leon/miniconda3/pkgs/gudhi-3.4.1-py39h47373e2_1/include/gudhi
/home/leon/miniconda3/pkgs/gudhi-3.4.1-py39h47373e2_1/lib/python3.9/site-packages/gudhi
/home/leon/miniconda3/include/gudhi/home/leon/miniconda3/lib/python3.9/site-packages/gudhi
/usr/lib/python3/dist-packages/gudhi
/usr/local/include/gudhi
/usr/local/share/gudhi

These are the directories named gudhi present in my system. Could any of them be confusing python?

I'm confused because for me this would be a trivial problem, but apparently I'm wrong.

**Comment by mglisse** [comment]
Since you have both a case that works and one that fails, you need to debug the issue by bringing them closer to each other until the problem is apparent. That is, simplify the failing program until it contains just the import line (if you cannot, see which line makes it work when you remove it), simplify the script until it just starts that program, etc. Try various things like manually executing `python3 file.py` vs `./file.py`, changing the current directory, printing the python version from the program to confirm that it is using the version you think, etc. At this point, the issue doesn't look very specific to gudhi, and I don't think I can be much help remote-debugging it...
You do appear to have installed gudhi at least 3 times (ubuntu, conda, and once from source).

**Comment by mglisse** [comment]
Did you find out what the issue was? (asking in case someone else hits the same issue and ends up here)

**Comment by poeiradonorte** [comment]
No. I even downloaded the docker version of gudhi, but the same error persists.

Just now, I contacted the authors of the article I'm trying to reproduce for help.

I think if the problem isn't in gudhi or my machine, it can only be in the model I'm trying to reproduce.

This at first glance strikes me as a trivial problem, but in fact it turns out to be a reasonably complex problem.
