### ISSUE TITLE
Construct Alpha Complex from CGAL Delaunay Triangulation

### ISSUE THREAD

**Issue by FreyaBretz** [GUDHI/gudhi-devel#634]
I would like to build a Delaunay triangulation with CGAL, manipulate it a little, so that it is Delaunay with respect to a larger point cloud,
and then use GUDHI to construct an Alpha complex from it (and actually compute persistence for it).

I took a look into the code for Alpha complexes and it seems to be possible to add another constructor which does that.
Do you think that there might arise some problems that I am missing?

One would have to make sure that the second part of the init_from_range function still works.
Thanks!

**Comment by VincentRouvreau** [comment]
> I would like to build a Delaunay triangulation with CGAL, manipulate it a little, so that it is Delaunay with respect to a larger point cloud, and then use GUDHI to construct an Alpha complex from it (and actually compute persistence for it).

I imagine that you are aware (it seems so from your question) that you can build a Delaunay complex with gudhi by saying for instance:
```cpp
struct MyOptions : Gudhi::Simplex_tree_options_full_featured {
  // Implicitly use 0 as filtration value for all simplices
  static const bool store_filtration = false;
};

int main() {
  ...
  Gudhi::alpha_complex::Alpha_complex<Kernel> delaunay_complex_from_points(points);

  Gudhi::Simplex_tree<MyOptions> simplex;
  if (alpha_complex_from_points.create_complex(simplex,
                                               std::numeric_limits<Gudhi::Simplex_tree<>::Filtration_value>::infinity(),
                                               false,    // exact
                                               true)) {  // default filtration is true => Delaunay complex
    ....
```

> I took a look into the code for Alpha complexes and it seems to be possible to add another constructor which does that. Do you think that there might arise some problems that I am missing?
> One would have to make sure that the second part of the init_from_range function still works. Thanks!

What we do is spatial sorting points given as an input. Then insert in a loop all points one by one and store its index in the `data()` field of each vertex. `vertex_handle_to_iterator_` allows the  `get_point` method to retrieve a point from a vertex (where vertex 10 in the simplex tree is point[0.5, 1.2, 2.3] for instance).
I think it is possible, but if you want the `get_point` to still work, maybe you would have to pass the triangulation and the points range as well as an input to this constructor.

**Comment by mglisse** [comment]
> I would like to build a Delaunay triangulation with CGAL, manipulate it a little, so that it is Delaunay with respect to a larger point cloud, and then use GUDHI to construct an Alpha complex from it (and actually compute persistence for it).

Hello,

could you clarify what you mean by this? The alpha-complex is uniquely defined. If you modify the triangulation on the same point set, it won't be Delaunay and you cannot get an alpha-complex anymore. Or do you mean that you build the Delaunay triangulation, then add/move/remove points while maintaining the Delaunay property, and then you want the alpha-complex of this new point set, and you are hoping to avoid recomputing the Delaunay triangulation since you already have it? That sounds doable, but it forces you to use exactly the same Triangulation type as Alpha_complex, which may not be the best suited for your manipulations. Or we would need to allow the user to specify the triangulation type, which forces to reorganize the code quite a bit. On the other hand, from memory, the computation of the Delaunay triangulation is usually faster than the computation of the filtration values, so there may not be that much to save by avoiding to recompute it.

**Comment by VincentRouvreau** [comment]
I will open a new issue to explain the need of a Delaunay complex
