### ISSUE TITLE
Atol `__call__` method needs explicit `.fit()` call first

### ISSUE THREAD

**Issue by astamm** [GUDHI/gudhi-devel#794]
Usually you can use the `__call__()` method of a class without calling `.fit()` yourself. But it seems no to work in `Atol`.

**Comment by mglisse** [comment]
`__call__` is here as a shortcut when you want `transform` for a single measure instead of a list of measures. We could be more explicit about the fact that calling `fit` first is necessary, but I don't really see what other behavior is possible. Automatically fitting on the measure passed in the first `__call__` could work, but it feels misleading.

**Comment by astamm** [comment]
Yes I understand the role of `__call__` but the way it is used in `Atol` is not really a shortcut. It basically should perform behind the scene `atol.fit_transform([measure])[0]`. If the user has to call the `.fit()` method himself then `__call__` is not really a *shortcut* anymore. I believe it is implemented in **scikit-learn** and in **gudhi.representations** (except for `Atol`) such that the user does not have to call `.fit()` himself.
Now I understand that in some cases the user might not want to overwrite all the attributes that would have been set by a previous call to `.fit()` with potentially more measures. So we could give `__call__` an extra optional argument `overwrite` which could be `True` by default in which case it internally calls `.fit()` on the `self` class. If the user however specifies explicitly `overwrite = False` then `__call__` could make a deep clone of the class and call `.fit()` on that clone. Does that make sense?

**Comment by mglisse** [comment]
> Yes I understand the role of `__call__` but the way it is used in `Atol` is not really a shortcut. It basically should perform behind the scene `atol.fit_transform([measure])[0]`. If the user has to call the `.fit()` method himself then `__call__` is not really a _shortcut_ anymore. I believe it is implemented in **scikit-learn** and in **gudhi.representations** (except for `Atol`) such that the user does not have to call `.fit()` himself.

We have a `__call__` that automatically does `fit` for some classes where `fit` does very little, that's not the best reference. If I look randomly at PersistenceImage, `fit` is written in a way that the second call to `fit` is ignored, which IIUC is actually bogus, sklearn wants a second call to `fit` to have the same result as starting from a clean object.

`atol(m)` is a shortcut for `atol.transform([m])[0]`. We could have named it `atol.transform_one(m)`, but then it wouldn't be much of a shortcut.

I don't think sklearn provides `__call__` in any class where it also provides `transform`.

> Now I understand that in some cases the user might not want to overwrite all the attributes that would have been set by a previous call to `.fit()` with potentially more measures. So we could give `__call__` an extra optional argument `overwrite` which could be `True` by default in which case it internally calls `.fit()` on the `self` class. If the user however specifies explicitly `overwrite = False` then `__call__` could make a deep clone of the class and call `.fit()` on that clone. Does that make sense?

I think we need to take a step back. The goal of ATOL is first to determine some good centers, and then use those to vectorize a bunch of diagrams (or other measures). Vectorizing just one measure based on itself is useless. Using just 1 measure for fit is already questionable, though possible. In my opinion, using `__call__` without `fit` is most likely to be an oversight (or a misunderstanding) on the user's part, and it is more helpful to let the user know there is a problem rather than silently do something that may not be what they expect. If this function does not suit them, they can stick to the normal fit+transform interface.

Let me ping @martinroyer , the author, in case he wants to chime in.

**Comment by astamm** [comment]
I totally understand your point. I guess what bugs me is that, despite `Atol` being put in the representations module, the use of `__call__` differs from any other class in that module. Hence, it breaks the common interface.
I had already concerns with putting `Atol` in that module, since it can actually vectorise measures that are not only persistence diagrams.

**Comment by astamm** [comment]
> `atol(m)` is a shortcut for `atol.transform([m])[0]`. We could have named it `atol.transform_one(m)`, but then it wouldn't be much of a shortcut.

If that is the goal of `__call__` here then it could be suppressed. It only does the subsetting after the transform and the user still needs to call `fit`. Plus, as you said, there is actually no point to call `Atol` on a single measure.

But then again, it would break the common API of the representations module which is already broken because `__call__` here is to be used differently from the other classes in the module.

**Comment by martinroyer** [comment]
> > Yes I understand the role of `__call__` but the way it is used in `Atol` is not really a shortcut. It basically should perform behind the scene `atol.fit_transform([measure])[0]`. If the user has to call the `.fit()` method himself then `__call__` is not really a _shortcut_ anymore. I believe it is implemented in **scikit-learn** and in **gudhi.representations** (except for `Atol`) such that the user does not have to call `.fit()` himself.
> 
> We have a `__call__` that automatically does `fit` for some classes where `fit` does very little, that's not the best reference. If I look randomly at PersistenceImage, `fit` is written in a way that the second call to `fit` is ignored, which IIUC is actually bogus, sklearn wants a second call to `fit` to have the same result as starting from a clean object.
> 
> `atol(m)` is a shortcut for `atol.transform([m])[0]`. We could have named it `atol.transform_one(m)`, but then it wouldn't be much of a shortcut.
> 
> I don't think sklearn provides `__call__` in any class where it also provides `transform`.
> 
> > Now I understand that in some cases the user might not want to overwrite all the attributes that would have been set by a previous call to `.fit()` with potentially more measures. So we could give `__call__` an extra optional argument `overwrite` which could be `True` by default in which case it internally calls `.fit()` on the `self` class. If the user however specifies explicitly `overwrite = False` then `__call__` could make a deep clone of the class and call `.fit()` on that clone. Does that make sense?
> 
> I think we need to take a step back. The goal of ATOL is first to determine some good centers, and then use those to vectorize a bunch of diagrams (or other measures). Vectorizing just one measure based on itself is useless. Using just 1 measure for fit is already questionable, though possible. In my opinion, using `__call__` without `fit` is most likely to be an oversight (or a misunderstanding) on the user's part, and it is more helpful to let the user know there is a problem rather than silently do something that may not be what they expect. If this function does not suit them, they can stick to the normal fit+transform interface.
> 
> Let me ping @martinroyer , the author, in case he wants to chime in.

Thank you Marc, unfortunately I do not think I can bring anything better than what you just did, I fully agree with your answer.

I liked having a shortcut for vectorizing a single measure but if `__call__` turns out to be too misleading in this context I have nothing against replacing it with `transform_one` instead. But unless I am mistaken it _is_ consistent with the other classes in the module.

**Comment by astamm** [comment]
Thank you @martinroyer. Well in the other classes of the module, `__call__` calls the `fit` internally or `fit` does not do anything, resulting in `__call__` behaving as `fit_transform([m])[0]`.
In `Atol`, it behaves like `transform([m])[0]` which requires the user to run `fit` before which is counterintuitive in my opinion.
Have a `transform_one` method would make Atol again different from the rest of the classes in the module. And the added benefits with respect to typing `transform([m])[0]` is negligible I think.

**Comment by mglisse** [comment]
We will have to discuss with @MathieuCarriere, I think if there is an issue, it is more with the other classes and not with Atol.

> Implementing a `transform_one` method would make Atol again different from the rest of the classes in the module.

I don't see what's so wrong about a class having extra functionality, in addition to the common functionality. For instance, in the class `Entropy`, after `fit`, you can access the member `grid_` to see what grid was used for the discretization. That's not part of the fit-transform concept, it would make no sense for `TopologicalVector`, but it is still useful to have it in `Entropy`.
