### ISSUE TITLE
[Python wheels] Python 3.12 

### ISSUE THREAD

**Issue by DavidLapous** [GUDHI/gudhi-devel#998]
Wheels are missing for python 3.12. 
Furthermore, the last available sources are gudhi 3.8rc1, 
which doesn't compile on python 3.12, and can be confusing.

Another topic, python 3.6 and 3.7 are [not supported anymore](https://devguide.python.org/versions/#unsupported-versions), 
do you know if there are still users using these versions **for good reasons** ? 
Otherwise, we can drop their support.

**Comment by mglisse** [comment]
> Wheels are missing for python 3.12.

There are conda packages, but yes, no pip packages. The way @VincentRouvreau  set things up, we basically build pip packages when we do a release and at no other time. I don't know if it would be easy to separate them, or do mini branch releases just for the sake of pip. For now, we are thinking of doing a 3.9 release soon-ish.

Note that many other packages don't support 3.12 yet.

> Furthermore, the last available sources are gudhi 3.8rc1,

That's a bit misleading :disappointed: (why not 3.8?)

> which doesn't compile on python 3.12,

If I remember correctly, the problem is not python 3.12 but cython 3.

> Another topic, python 3.6 and 3.7 are [not supported anymore](https://devguide.python.org/versions/#unsupported-versions), do you know if there are still users using these versions **for good reasons** ? Otherwise, we can drop their support.

:+1:

**Comment by VincentRouvreau** [comment]
Yes the cython 3 issue is #916

**Comment by djawdjjalodkpsaodkpw** [comment]
There are conda packages, but yes, no pip packages. The way @VincentRouvreau set things up, we basically build pip packages when we do a release and at no other time. I don't know if it would be easy to separate them, or do mini branch releases just for the sake of pip. For now, we are thinking of doing a 3.9 release soon-ish.

Note that many other packages don't support 3.12 yet.
